import type { Metadata } from "next";
import { IBM_Plex_Sans_Thai } from "next/font/google"
import "../globals.css";


const ibm = IBM_Plex_Sans_Thai({ weight: ["400", "700"], subsets: ["thai"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${ibm.className} bg-whereWhite h-[100vh] max-w-lg mx-auto border overscroll-none`}>
        {children}
      </body>
    </html>
  );
}
